apiVersion: v1
kind: Namespace
metadata:
  name: reactive-memory

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactive
  namespace: reactive-memory
spec:
  selector:
    matchLabels:
      app: reactive
  replicas: 1
  template:
    metadata:
      labels:
        app: reactive
    spec:
      containers:
      - name: reactive
        image: mhus/reactive-playground:7.0.0-SNAPSHOT
        ports:
        - containerPort: 8181
        stdin: true
        tty: true

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: reactive
  name: reactive-ui
  namespace: reactive-memory
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
    - port: 8181
      targetPort: 8181
  selector:
    app: reactive
